{
  "_args": [
    [
      {
        "raw": "node-exceptions@^2.0.0",
        "scope": null,
        "escapedName": "node-exceptions",
        "name": "node-exceptions",
        "rawSpec": "^2.0.0",
        "spec": ">=2.0.0 <3.0.0",
        "type": "range"
      },
      "/home/brenda/Proyecto_PedidosReservaciones/node_modules/adonis-ace"
    ]
  ],
  "_from": "node-exceptions@>=2.0.0 <3.0.0",
  "_id": "node-exceptions@2.0.2",
  "_inCache": true,
  "_location": "/node-exceptions",
  "_nodeVersion": "8.0.0",
  "_npmOperationalInternal": {
    "host": "s3://npm-registry-packages",
    "tmp": "tmp/node-exceptions-2.0.2.tgz_1497264381965_0.15966099058277905"
  },
  "_npmUser": {
    "name": "virk",
    "email": "virk@adonisjs.com"
  },
  "_npmVersion": "5.0.0",
  "_phantomChildren": {},
  "_requested": {
    "raw": "node-exceptions@^2.0.0",
    "scope": null,
    "escapedName": "node-exceptions",
    "name": "node-exceptions",
    "rawSpec": "^2.0.0",
    "spec": ">=2.0.0 <3.0.0",
    "type": "range"
  },
  "_requiredBy": [
    "/adonis-ace",
    "/adonis-lucid"
  ],
  "_resolved": "https://registry.npmjs.org/node-exceptions/-/node-exceptions-2.0.2.tgz",
  "_shasum": "2612b45929b774e3669557f852b47507765acfe7",
  "_shrinkwrap": null,
  "_spec": "node-exceptions@^2.0.0",
  "_where": "/home/brenda/Proyecto_PedidosReservaciones/node_modules/adonis-ace",
  "author": {
    "name": "amanvirk,adonisjs"
  },
  "bugs": {
    "url": "https://github.com/poppinss/node-exceptions/issues"
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  },
  "dependencies": {},
  "description": "Extendable error class for nodejs to extend native errors",
  "devDependencies": {
    "coveralls": "^2.11.6",
    "cz-conventional-changelog": "^1.1.5",
    "japa": "^1.0.3",
    "japa-cli": "^1.0.1",
    "nyc": "^10.2.0",
    "standard": "^5.4.1"
  },
  "directories": {
    "test": "test"
  },
  "dist": {
    "integrity": "sha512-nILccFLvnaOBoKZZtWfZipn/hlThZOT6UJOLX6SA3yLMYPcvLTIF26PXx73sPnAg45p05iYFYw2jvayNHz4rDA==",
    "shasum": "2612b45929b774e3669557f852b47507765acfe7",
    "tarball": "https://registry.npmjs.org/node-exceptions/-/node-exceptions-2.0.2.tgz"
  },
  "gitHead": "357a1f4f4c4cce7ade0a185db6ea39ae3ca08ef8",
  "homepage": "https://github.com/poppinss/node-exceptions#readme",
  "keywords": [
    "exception",
    "node-errors",
    "custom-errors",
    "Error"
  ],
  "license": "MIT",
  "main": "index.js",
  "maintainers": [
    {
      "name": "virk",
      "email": "virk@adonisjs.com"
    }
  ],
  "name": "node-exceptions",
  "optionalDependencies": {},
  "readme": "# Node Exceptions\n\n[![NPM Version][npm-image]][npm-url]\n[![Build Status][travis-image]][travis-url]\n[![Appveyor][appveyor-image]][appveyor-url]\n[![Coveralls][coveralls-image]][coveralls-url]\n\n<a href=\"http://i1117.photobucket.com/albums/k594/thetutlage/poppins-1_zpsg867sqyl.png\">\n<img src=\"http://i1117.photobucket.com/albums/k594/thetutlage/poppins-1_zpsg867sqyl.png\" width=\"300px\" align=\"right\" vspace=\"20px\" />\n</a>\n\nThrowing errors in Javascript does not give much information about the error type as it is really hard to throw custom exceptions. Node Exceptions is a tiny wrapper which will let you extend the Error class and throw custom errors.\n\n## Why custom errors\nErrors are thrown anywhere inside the code and handling them properly is required. For example you have an HTTP application, which can throw multiple errors and in order to handle those errors gracefully, you need to know the error types or their names.\n\n```javascript\nswitch (err.name) {\n  case 'HttpException':\n    // do something\n  case 'RunTimeException':\n    // do something else\n}\n```\n\n\n## Install\n\n```bash\nnpm i --save node-exceptions\n```\n\n## Creating custom errors\n\n```javascript\nconst NE = require('node-exceptions')\n\nclass MyCustomError extends NE.LogicalException {}\n\ntry {\n  throw new MyCustomError('Something bad happened')\n} catch (e) {\n  console.log(e.status) // equals 500\n  console.log(e.name) // equals MyCustomError\n  console.log(e.message) // Something bad happened\n  console.log(e.stack) // Error stack with correct reference to filepath and linenum\n  console.log(e.toString()) // MyCustomError: Something bad happened\n}\n```\n\n## Custom error status\nIt is also possible to have a custom error status when throwing exceptions.\n\n```javascript\nconst NE = require('node-exceptions')\n\nclass HttpException extends NE.LogicalException {}\n\ntry {\n  throw new HttpException('Page not found', 404)\n} catch (e) {\n  console.log(e.status) // equals 404\n}\n```\n\nAlso `NE` comes with some commonly required Exception classes which includes.\n\n#### DomainException \nWhen something excepted has failed. For example image upload mismatch extension.\n\n```javascript\nthrow new NE.DomainException()\n```\n\n#### InvalidArgumentException\nMethod arguments are invalid or incomplete.\n\n```javascript\nthrow new NE.InvalidArgumentException()\n```\n\n#### RangeException\nError caused due to arithmetic operations.\n\n```javascript\nthrow new NE.RangeException()\n```\n\n#### RuntimeException\nAn error occured after all required checks.\n\n```javascript\nthrow new NE.RuntimeException()\n```\n\n#### HttpException\nHttp specific errors.\n\n```javascript\nthrow new NE.HttpException()\n```\n\n[appveyor-image]: https://img.shields.io/appveyor/ci/thetutlage/node-exceptions/master.svg?style=flat-square\n\n[appveyor-url]: https://ci.appveyor.com/project/thetutlage/node-exceptions\n\n[npm-image]: https://img.shields.io/npm/v/node-exceptions.svg?style=flat-square\n[npm-url]: https://npmjs.org/package/node-exceptions\n\n[travis-image]: https://img.shields.io/travis/poppinss/node-exceptions/master.svg?style=flat-square\n[travis-url]: https://travis-ci.org/poppinss/node-exceptions\n\n[coveralls-image]: https://img.shields.io/coveralls/poppinss/node-exceptions/develop.svg?style=flat-square\n\n[coveralls-url]: https://coveralls.io/github/poppinss/node-exceptions%",
  "readmeFilename": "README.md",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/poppinss/node-exceptions.git"
  },
  "scripts": {
    "coverage": "nyc report --reporter=text-lcov | coveralls",
    "lint": "standard",
    "posttest": "npm run coverage",
    "pretest": "npm run lint",
    "test": "nyc npm run test:local",
    "test:local": "japa",
    "test:win": "node ./node_modules/japa-cli/index.js"
  },
  "version": "2.0.2"
}
